name: ml_app
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pycaret
  - pandas
  - sklearn
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipykernel
  - networkx
  - streamlit=1.29
  - streamlit_pandas_profiling
  - ydata_profiling

